version: '3.8'

services:
  postgres_db:
    image: postgres:16-alpine
    container_name: kinikit_postgres_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: kinikittest
      POSTGRES_PASSWORD: kinikittest
      POSTGRES_DB: kinikittest
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

  mysql_db:
    image: mysql:8.0
    container_name: kinikit_mysql_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: k1n1k1tt3st
      MYSQL_DATABASE: kinikittest
      MYSQL_USER: kinikittest
      MYSQL_PASSWORD: kinikittest
    ports:
      - "3310:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
    driver:
      local
  postgres_data:
    driver:
      local